spring:
  application:
    name: happy-happy-karate-soup-backend

server:
  port: 8080

app:
  charts:
    cache-seconds:
      list: 60
      detail: 300

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
