export const FOOD_EMOJIS = [
  // --- 野菜・根菜 ---
  { id: 'item-1', emoji: '🥕', label: 'にんじん' },
  { id: 'item-2', emoji: '🧅', label: 'たまねぎ' },
  { id: 'item-3', emoji: '🥔', label: 'じゃがいも' },
  { id: 'item-4', emoji: '🍅', label: 'トマト' },
  { id: 'item-5', emoji: '🍆', label: 'なす' },
  { id: 'item-6', emoji: '🌽', label: 'とうもろこし' },
  { id: 'item-7', emoji: '🥦', label: 'ブロッコリー' },
  { id: 'item-8', emoji: '🥬', label: 'レタス' },
  { id: 'item-9', emoji: '🍄', label: 'きのこ' },
  { id: 'item-10', emoji: '🥑', label: 'アボカド' },
  { id: 'item-11', emoji: '🫑', label: 'ピーマン' },
  { id: 'item-12', emoji: '🥒', label: 'きゅうり' },
  { id: 'item-13', emoji: '🍠', label: 'さつまいも' },
  { id: 'item-14', emoji: '🧄', label: 'にんにく' },
  { id: 'item-15', emoji: '🌶️', label: 'とうがらし' },
  { id: 'item-16', emoji: '🎃', label: 'かぼちゃ' },
  { id: 'item-17', emoji: '🥗', label: 'サラダ' },
  { id: 'item-18', emoji: '🎋', label: 'たけのこ' },

  // --- お肉 ---
  { id: 'item-19', emoji: '🍖', label: '骨付き肉' },
  { id: 'item-20', emoji: '🥩', label: 'ステーキ' },
  { id: 'item-21', emoji: '🍗', label: 'チキン' },
  { id: 'item-22', emoji: '🥓', label: 'ベーコン' },
  { id: 'item-23', emoji: '🌭', label: 'ソーセージ' },

  // --- 魚介類 ---
  { id: 'item-24', emoji: '🐟', label: 'さかな' },
  { id: 'item-25', emoji: '🦐', label: 'えび' },
  { id: 'item-26', emoji: '🦀', label: 'かに' },
  { id: 'item-27', emoji: '🐙', label: 'たこ' },
  { id: 'item-28', emoji: '🦑', label: 'いか' },
  { id: 'item-29', emoji: '🐚', label: 'ほたて' },
  { id: 'item-30', emoji: '🦪', label: 'かき' },

  // --- 果物 ---
  { id: 'item-31', emoji: '🍎', label: 'りんご' },
  { id: 'item-32', emoji: '🍏', label: '青りんご' },
  { id: 'item-33', emoji: '🍊', label: 'みかん' },
  { id: 'item-34', emoji: '🍋', label: 'レモン' },
  { id: 'item-35', emoji: '🍌', label: 'バナナ' },
  { id: 'item-36', emoji: '🍉', label: 'すいか' },
  { id: 'item-37', emoji: '🍇', label: 'ぶどう' },
  { id: 'item-38', emoji: '🍓', label: 'いちご' },
  { id: 'item-39', emoji: '🍈', label: 'メロン' },
  { id: 'item-40', emoji: '🍒', label: 'さくらんぼ' },
  { id: 'item-41', emoji: '🍑', label: 'もも' },
  { id: 'item-42', emoji: '🍍', label: 'パイナップル' },
  { id: 'item-43', emoji: '🥭', label: 'マンゴー' },
  { id: 'item-44', emoji: '🥝', label: 'キウイ' },
  { id: 'item-45', emoji: '🍐', label: 'なし' },
  { id: 'item-46', emoji: '🫐', label: 'ブルーベリー' },

  // --- 主食・麺・パン ---
  { id: 'item-47', emoji: '🍙', label: 'おにぎり' },
  { id: 'item-48', emoji: '🍚', label: 'ごはん' },
  { id: 'item-49', emoji: '🍜', label: 'ラーメン' },
  { id: 'item-50', emoji: '🍝', label: 'パスタ' },
  { id: 'item-51', emoji: '🍛', label: 'カレー' },
  { id: 'item-52', emoji: '🍞', label: '食パン' },
  { id: 'item-53', emoji: '🥐', label: 'クロワッサン' },
  { id: 'item-54', emoji: '🥖', label: 'フランスパン' },
  { id: 'item-55', emoji: '🥯', label: 'ベーグル' },
  { id: 'item-56', emoji: '🥨', label: 'プレッツェル' },
  { id: 'item-57', emoji: '🥞', label: 'パンケーキ' },
  { id: 'item-58', emoji: '🍕', label: 'ピザ' },
  { id: 'item-59', emoji: '🍔', label: 'ハンバーガー' },
  { id: 'item-60', emoji: '🍟', label: 'フライドポテト' },
  { id: 'item-61', emoji: '🥪', label: 'サンドイッチ' },
  { id: 'item-62', emoji: '🌮', label: 'タコス' },
  { id: 'item-63', emoji: '🌯', label: 'ブリトー' },

  // --- 卵・乳製品・その他調理品 ---
  { id: 'item-64', emoji: '🍳', label: '目玉焼き' },
  { id: 'item-65', emoji: '🥚', label: 'たまご' },
  { id: 'item-66', emoji: '🧀', label: 'チーズ' },
  { id: 'item-67', emoji: '🧈', label: 'バター' },
  { id: 'item-68', emoji: '🥟', label: 'ぎょうざ' },
  { id: 'item-69', emoji: '🍣', label: 'おすし' },
  { id: 'item-70', emoji: '🍤', label: 'えびふらい' },
  { id: 'item-71', emoji: '🍥', label: 'なると' },
  { id: 'item-72', emoji: '🍢', label: 'おでん' },
  { id: 'item-73', emoji: '🥘', label: 'パエリア' },
  { id: 'item-74', emoji: '🍲', label: 'なべ' },
  { id: 'item-75', emoji: '🍜', label: 'うどん' },

  // --- お菓子・デザート ---
  { id: 'item-76', emoji: '🍦', label: 'ソフトクリーム' },
  { id: 'item-77', emoji: '🍧', label: 'かき氷' },
  { id: 'item-78', emoji: '🍨', label: 'アイス' },
  { id: 'item-79', emoji: '🍩', label: 'ドーナツ' },
  { id: 'item-80', emoji: '🍪', label: 'クッキー' },
  { id: 'item-81', emoji: '🎂', label: 'ケーキ' },
  { id: 'item-82', emoji: '🍰', label: 'ショートケーキ' },
  { id: 'item-83', emoji: '🧁', label: 'カップケーキ' },
  { id: 'item-84', emoji: '🥧', label: 'パイ' },
  { id: 'item-85', emoji: '🍫', label: 'チョコ' },
  { id: 'item-86', emoji: '🍬', label: 'キャンディ' },
  { id: 'item-87', emoji: '🍭', label: 'ペロペロキャンディ' },
  { id: 'item-88', emoji: '🍮', label: 'プリン' },
  { id: 'item-89', emoji: '🍯', label: 'はちみつ' },
  { id: 'item-90', emoji: '🍡', label: 'だんご' },
  { id: 'item-91', emoji: '🍘', label: 'せんべい' },
  { id: 'item-92', emoji: '🍿', label: 'ポップコーン' },

  // --- 飲み物・その他 ---
  { id: 'item-93', emoji: '☕', label: 'コーヒー' },
  { id: 'item-94', emoji: '🍵', label: 'お茶' },
  { id: 'item-95', emoji: '🥤', label: 'コーラ' },
  { id: 'item-96', emoji: '🧃', label: 'ジュース' },
  { id: 'item-97', emoji: '🥛', label: 'ミルク' },
  { id: 'item-98', emoji: '🍺', label: 'ビール' },
  { id: 'item-99', emoji: '🍷', label: 'ワイン' },
  { id: 'item-100', emoji: '🧂', label: 'しお' },
];